# Generated by Django 2.2.1 on 2019-05-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_verbose_names_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='image',
            field=models.ImageField(null=True, upload_to='cinema_images/', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='temporary.jpg', upload_to='movie_posters/', verbose_name='پوستر'),
            preserve_default=False,
        ),
    ]
